name: Node.js CI

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Build Lib
        run: npm ci && npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist

  test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Execute Tests
        run: npm ci && npm run test
        working-directory: tests

  deploy-npm:
    needs: [test]
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./dist

      - name: Publish Package
        run: npm publish

    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  deploy-github:
    needs: [test]
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://npm.pkg.github.com/"

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./dist

      - name: Modify package.json for GitHub
        run: |
          jq '.name="@2and4/web-engine-canvas"' package.json > temp.json && mv temp.json package.json

      - name: Publish Package
        run: npm publish

    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
